### PR TITLE
Bump xml version to 6.1.0.

### PR DESCRIPTION
**Pull request by Phil9l**

### CODE REVIEW

**Comment by creativeinfix** [comment]
When it will get approved?

**Comment by Phil9l** [comment]
> When it will get approved?

This repo doesn't look very active. I just use a dependency from a ref now:
```
  minio:
    git:
      url: https://github.com/xtyxtyx/minio-dart.git
      ref: af756cb
```

**Comment by vanlooverenkoen** [comment]
This should be merged. Working with flutter_svg & minio is causing conflicts at the moment. thanks @Phil9l for your fix

**Comment by mkbsugita** [comment]
why does it require 5.0.2?

**Comment by Phil9l** [comment]
> why does it require 5.0.2?

Probably it was the latest version when the repo was still maintained.

**Comment by mkbsugita** [comment]
I did
```
dependency_overrides:
  xml: ^6.0.1
```

but when I use `putObject` it occurs it....
```
minio.putObject error: XmlParserException: ">" expected at 1:16
```

**Pull request closed without merging**
